src/app/chariot/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.views import static

from deployments.views import DeploymentListView
from hubs.views import HubCreateView
from .views import login_view, create_admin_view, DeviceListView

admin.autodiscover()

urlpatterns = [
    url(r'^$', DeploymentListView.as_view(), name='home'),
    url(r'^accounts/create/$', create_admin_view, name='auth_create_admin'),
    url(r'^accounts/login/$', login_view, name='auth_login'),
    url(r'^accounts/logout/$', logout_then_login, name='auth_logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('hubs.urls', namespace='hubs')),
    url(r'^deployments/', include('deployments.urls', namespace='deployments')),
    url(r'^devices', DeviceListView.as_view(), name='devices'),
    url(r'^graphs/', include('graphs.urls', namespace='graphs')),
    url(r'^hub/create', HubCreateView.as_view(), name='create_hub'),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
]

src/app/deployments/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^create', DeploymentCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)$', DeploymentView.as_view(), name='view'),
    url(r'^(?P<pk>\d+)/update', DeploymentUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/end$', DeploymentEndView.as_view(), name='end'),
    url(r'^(?P<pk>\d+)/start$', DeploymentStartView.as_view(), name='start'),
    url(r'^(?P<pk>\d+)/fragment$', DeploymentDetailView.as_view(), name='fragment'),
    url(r'^(?P<pk>\d+)/sensor/(?P<id>\d+)$', DeploymentSensorView.as_view(), name='sensor'),

    url(r'^annotation$', DeploymentAnnotationCreate.as_view(), name='annotation-create'),
    url(r'^annotation/(?P<pk>\d+)$', DeploymentAnnotationUpdate.as_view(),
        name='annotation-update'),
    url(r'^annotation/(?P<pk>\d+)/delete$', DeploymentAnnotationDelete.as_view(),
        name='annotation-delete'),
]

src/app/hubs/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^deployments', DeploymentListView.as_view(), name='deployments'),
    url(r'^deployment/(?P<pk>\d+)$', DeploymentView.as_view(), name='data'),
    url(r'^deployment/(?P<pk>\d+)/data', DataView.as_view(), name='data'),
    url(r'^deployment/(?P<pk>\d+)/latest', LatestDataView.as_view(), name='latest'),
    url(r'^deployment/(?P<pk>\d+)/prediction', DeploymentPrediction.as_view(), name='prediction'),
    url(r'^hub/(?P<id>[\w:-]+)/ping', HubPingView.as_view(), name='ping'),
    url(r'^hub/(?P<id>[\w:-]+)/sensors', SensorListView.as_view(), name='sensors'),
    url(r'^hub/(?P<id>[\w:-]+)/token', get_token, name='token'),
    url(r'^reading', SensorReading.as_view(), name='reading'),
]

src/app/deployments/models.py
# encoding:UTF-8
import datetime

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from chariot.influx import select

from hubs.models import Hub
from sensors.models import Sensor
from chariot.influx import drop_from

class Deployment(models.Model):
    BOILER_TYPES = (
        (1, _("Gas")),
        (2, _("Electric"))
    )

    client_name = models.CharField(max_length=255)
    address_line_one = models.CharField(max_length=255)
    post_code = models.CharField(max_length=255)
    notes = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    photo = models.ImageField(_('Header Image'), null=True, blank=True,
                              upload_to='deployment_photos')

    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)

    boiler_manufacturer = models.CharField(max_length=255, null=True, blank=True)
    boiler_model = models.CharField(max_length=255, null=True, blank=True)
    boiler_output = models.FloatField(null=True, blank=True)
    boiler_efficiency = models.FloatField(null=True, blank=True)
    boiler_type = models.IntegerField(choices=BOILER_TYPES, default=1)

    building_area = models.FloatField(default=0)
    building_height = models.FloatField(default=0)

    hub = models.OneToOneField(Hub, blank=True, null=True)

    prediction = models.TextField(null=True, blank=True)

    def __str__(self):
        return '{client} Deployment'.format(client=self.client_name)

    def end(self):
        if not self.running:
            raise ValueError('Deployment is not running')

        self.hub = None
        self.end_date = timezone.datetime.now()
        self.save()

    @property
    def running(self):
        return self.start_date is not None and self.end_date is None

    def start(self):
        if self.running:
            raise ValueError('Deployment is already running')

        for sensor in self.sensors.all():
            for channel in sensor.sensor.channels.all():
                drop_from(channel.name).where('deployment').eq(self.pk)

        self.start_date = timezone.datetime.now()
        self.save()

    @property
    def status(self):
        if self.end_date is not None:
            return 4, 'Deployment Ended'
        elif self.hub and self.sensors.exists():
            if self.running:
                return 3, 'Deployment Running'
            else:
                return 2, 'Deployment not running'

        return 1, 'Details Incomplete'


class DeploymentAnnotation(models.Model):
    text = models.TextField()
    start = models.DateTimeField()
    end = models.DateTimeField()
    layer = models.IntegerField()
    author = models.ForeignKey(User)
    deployment = models.ForeignKey(Deployment)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Deployment Annotations"


class DeploymentThermostatSetting(models.Model):
    deployment = models.ForeignKey(Deployment, related_name='thermostats')
    setting = models.FloatField(default=20)
    time = models.TimeField(default=datetime.time(16, 00))
    days = models.CharField(default='all', max_length=100)

    class Meta:
        verbose_name_plural = "Deployment Thermostat Settings"


class DeploymentSensor(models.Model):
    deployment = models.ForeignKey(Deployment, related_name='sensors')
    sensor = models.ForeignKey(Sensor)
    room_area = models.FloatField(default=0)
    room_height = models.FloatField(default=2.4)
    nearest_thermostat = models.BooleanField(default=False)
    cost = models.FloatField(default=0)
    location = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['sensor']
        verbose_name_plural = "Deployment Sensors"
        unique_together = ("deployment", "sensor")

    def __str__(self):
        return 'Sensor {sensor} for {deployment}'.format(
            sensor=self.sensor.name, deployment=self.deployment
        )

    @property
    def has_data(self):
        channels = []
        for channel in self.sensor.channels.all():
            try:
                result = select('LAST').from_table(channel.id) \
                    .where('deployment').eq(self.deployment.pk) \
                    .where('sensor').eq(self.sensor.id).first()
                if result:
                    channels.append(channel)
            except Exception as e:
                pass

        return len(channels) > 0

    @property
    def latest_reading(self):
        latest_reading = {}

        for channel in self.sensor.channels.all():
            try:
                result = select('LAST').from_table(channel.id) \
                    .where('deployment').eq(self.deployment.pk) \
                    .where('sensor').eq(self.sensor.id).first()
                if result:
                    if not latest_reading or result['time'] > latest_reading['time']:
                        latest_reading = {
                            'channel': channel,
                            'result': result,
                            'time': datetime.datetime.fromtimestamp(result['time']/1000.0),
                            'value': result['last']
                        }
            except Exception as e:
                pass

        return latest_reading

    @property
    def latest_readings(self):
        latest_readings = []

        for channel in self.sensor.channels.all():
            try:
                result = select('LAST').from_table(channel.id) \
                    .where('deployment').eq(self.deployment.pk) \
                    .where('sensor').eq(self.sensor.id).first()
                latest_readings.append({
                    'channel': channel,
                    'result': result,
                    'time': result['time'],
                    'value': result['last']
                })
            except Exception as e:
                latest_readings.append({
                    'channel': channel,
                    'e': repr(e)
                })

        return latest_readings

    def save(self, *args, **kwargs):
        if not self.id:
            try:
                DeploymentSensor.objects.get(
                    deployment=self.deployment,
                    sensor=self.sensor
                )
                raise ValidationError('A SensorDeployment with that deployment and sensor combo already exists')
            except DeploymentSensor.DoesNotExist:
                pass

        super(DeploymentSensor, self).save(*args, **kwargs)

src/app/deployments/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.views.generic.edit import BaseUpdateView

from chariot.mixins import BackButtonMixin, LoginRequiredMixin
from .forms import *
from .models import Deployment, DeploymentThermostatSetting

import json


class DeploymentView(LoginRequiredMixin, BackButtonMixin, DetailView):
    model = Deployment
    template_name = 'deployments/deployment_view.html'

    def get_back_url(self):
        return reverse('home')


class DeploymentCreateView(LoginRequiredMixin, BackButtonMixin, CreateView):
    form_class = DeploymentCreateForm
    model = Deployment
    template_name = 'deployments/deployment_create.html'

    def get_back_url(self):
        return reverse('home')

    def get_success_url(self):
        return reverse('deployments:view', args=(self.object.id,))


class DeploymentEndView(LoginRequiredMixin, UpdateView):
    form_class = DeploymentEndForm
    model = Deployment

    def get_success_url(self):
        return reverse('deployments:view', args=(self.kwargs['pk'],))


class DeploymentListView(LoginRequiredMixin, ListView):
    context_object_name = 'deployments'
    model = Deployment
    template_name = 'deployments/deployment_list.html'

    def get_context_data(self, **kwargs):
        context = super(DeploymentListView, self).get_context_data(**kwargs)
        context['deployments'] = Deployment.objects.all()
        return context


class DeploymentStartView(LoginRequiredMixin, UpdateView):
    form_class = DeploymentStartForm
    model = Deployment

    def get_success_url(self):
        return reverse('deployments:view', args=(self.kwargs['pk'],))


class DeploymentUpdateView(LoginRequiredMixin, BackButtonMixin, UpdateView):
    template_name = 'deployments/deployment_update.html'
    form_class = DeploymentUpdateForm
    model = Deployment

    def form_valid(self, form):
        instance = form.save(commit=False)
        for field in self.request.POST:
            if field.startswith('thermostat_time_'):
                index = field[16:]
                thermostat = DeploymentThermostatSetting()
                if 'thermostat_id_' + index in self.request.POST:
                    id = self.request.POST['thermostat_id_' + index]
                    thermostat = DeploymentThermostatSetting.objects.get(id=id)
                else:
                    thermostat = DeploymentThermostatSetting.objects.create(deployment=instance)

                thermostat.setting = float(self.request.POST['thermostat_temp_' + index])
                thermostat.time = self.request.POST['thermostat_time_' + index]
                thermostat.save()
        return super(DeploymentUpdateView, self).form_valid(form)

    def get_back_url(self):
        return reverse('deployments:view', args=(self.kwargs['pk'],))

    def get_success_url(self):
        return reverse('deployments:view', args=(self.kwargs['pk'],))


class DeploymentDetailView(LoginRequiredMixin, DetailView):
    model = Deployment
    template_name = 'deployments/deployment_fragment.html'


class DeploymentSensorView(BackButtonMixin, UpdateView):
    model = DeploymentSensor
    template_name = 'deployments/deployment_sensor.html'
    form_class = DeploymentSensorUpdateForm
    context_object_name = 'sensor'

    def get_back_url(self):
        return reverse('deployments:view', args=(self.kwargs['pk'],))

    def get_object(self, queryset=None):
        self.object = DeploymentSensor.objects.get(
            deployment=self.kwargs.get('pk', None),
            sensor=self.kwargs.get('id', None)
        )
        return self.object

    def post(self, request, *args, **kwargs):
        self.object = DeploymentSensor.objects.get(
            deployment=request.POST['deployment'],
            sensor=request.POST['sensor']
        )
        return super(BaseUpdateView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('deployments:view', args=(self.kwargs['pk'],))


class DeploymentAnnotationCreate(LoginRequiredMixin, CreateView):
    model = DeploymentAnnotation
    form_class = DeploymentAnnotationForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(DeploymentAnnotationCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('deployments:annotation-update', args=(self.object.id,))


class DeploymentAnnotationUpdate(LoginRequiredMixin, UpdateView):
    model = DeploymentAnnotation
    form_class = DeploymentAnnotationForm
    fields = ['start', 'end', 'layer', 'text', 'deployment']

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        annotation = {
            'id': self.object.pk,
            'text': self.object.text,
            'start': self.object.start.strftime("%Y-%m-%d %H:%M:%S"),
            'end': self.object.end.strftime("%Y-%m-%d %H:%M:%S"),
            'layer': self.object.layer,
            'deployment': self.object.deployment.pk
        }
        return HttpResponse(json.dumps(annotation), content_type='application/json')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(DeploymentAnnotationUpdate, self).form_valid(form)

    def form_invalid(self, form):
        form.instance.author = self.request.user
        return super(DeploymentAnnotationUpdate, self).form_invalid(form)

    def get_success_url(self):
        return reverse('deployments:annotation-update', args=(self.kwargs['pk'],))


class DeploymentAnnotationDelete(LoginRequiredMixin, DeleteView):
    model = DeploymentAnnotation
    success_url = 'temp'

    def delete(self, request, *args, **kwargs):
        super(DeploymentAnnotationDelete, self).delete(request, *args, **kwargs)

        return HttpResponse('"success"', content_type='application/json')

src/app/deployments/templates/deployments/deployment_create.html
{% extends 'chariot/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Deployment{% endblock %}

{% block content %}
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--6-col mdl-cell--3-offset-desktop mdl-cell--1-offset-tablet">
	    <form class="uniForm" method="post" enctype="multipart/form-data">

		    {% include "deployments/deployment_fields.html" with deployment=deployment %}

		    <input type="submit" value="Create" class="submit submitButton mdl-button mdl-js-button button_right mdl-button--raised mdl-button--colored" id="submit-id-add_hub">
	    </form>
    </div>
</div>
{% endblock content %}

src/app/deployments/templates/deployments/deployment_fields.html
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% csrf_token %}
<div id="div_id_photo" class="">
	<label id="label_id_photo" class="mdl-typography--title deployment-header mdl-color--blue-900"
			{% if form.photo.value %}
           style="background-image: url('{{ MEDIA_URL }}{{ form.photo.value }}')"
			{% endif %}
           for="id_photo">
		<i class="material-icons">file_upload</i>
		Header Image
	</label>

	<div style="display: none">
		{% crispy_field form.photo 'accept' 'image/*' %}
	</div>

	<script>
		var input = document.getElementById('id_photo');
		input.onchange = function () {
			var label = document.getElementById('label_id_photo');
			if (this.files.length > 0) {
				label.innerHTML = 'Header Image: ' + this.files[0].name;
			}
			else {
				label.innerHTML = 'Header Image';
			}
		};
	</script>
</div>
{% if form_show_errors %}
	{% for error in field.errors %}
		<p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="errorField">
			{{ error }}
		</p>
	{% endfor %}
{% endif %}

{{ form.non_field_errors }}

<div id="div_id_client_name" class="">
	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
		<label for="id_client_name" class="mdl-textfield__label requiredField">
			Client name
		</label>
		{% crispy_field form.client_name 'class' 'mdl-textfield__input' %}
	</div>
</div>

{% if not deployment %}
	<div id="div_id_hub" class="">
		<div style="padding-top: 8px" class="mdl-textfield mdl-js-textfield">
			<label class="mdl-typography--caption mdl-color-text--primary requiredField"
			       for="id_hub">
				Hub
			</label>
			<label class="mdl-textfield__label"></label>
			<div><i class="material-icons" style="position: absolute; right: 0; z-index: -10;">arrow_drop_down</i>
				{% crispy_field form.hub 'class' 'mdl-textfield__input' 'style' '-webkit-appearance: none; -moz-appearance: none; appearance: none; padding-right: 24px; border-radius: 0' %}
			</div>
		</div>
	</div>
{% endif %}

<div id="div_id_address_line_one" class="">
	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
		<label for="id_address_line_one" class="mdl-textfield__label requiredField">
			First Line of Address
		</label>
		{% crispy_field form.address_line_one 'class' 'mdl-textfield__input' %}
	</div>
</div>

<div id="div_id_post_code" class="">
	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
		<label for="id_post_code" class="mdl-textfield__label requiredField">
			Post code
		</label>
		{% crispy_field form.post_code 'class' 'mdl-textfield__input' %}
	</div>
</div>

<div style="display: flex">
	<div id="div_id_building_area" style="flex:1">
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<label for="id_building_area" class="mdl-textfield__label requiredField">
				Building area
			</label>
			<div style="display: flex">
				{% crispy_field form.building_area 'class' 'mdl-textfield__input' 'min' '0' 'style' 'text-align:right' %}
				<div style="margin-top: 3px; margin-left: 3px; color: #666;">m&#178;</div>
			</div>
		</div>
	</div>
	<div style="width: 16px">&nbsp</div>
	<div id="div_id_building_height" style="flex:1">
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<label for="id_building_height" class="mdl-textfield__label requiredField">
				Building height
			</label>
			<div style="display: flex">
				{% crispy_field form.building_height 'class' 'mdl-textfield__input' 'min' '0' 'style' 'text-align:right' %}
				<div style="margin-top: 3px; margin-left: 3px; color: #666;">m</div>
			</div>
		</div>
	</div>
</div>

<div class="mdl-typography--subhead">Thermostat</div>
{% for thermostat in deployment.thermostats.all %}
	<input type="hidden" name="thermostat_id_{{ forloop.counter }}" value="{{ thermostat.id }}" />
	<div style="display: flex">
		<div style="flex:1">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="id_thermostat_time_{{ forloop.counter }}"
				       class="mdl-textfield__label requiredField">
					Start Time
				</label>
				<div style="display: flex">
					<input name="thermostat_time_{{ forloop.counter }}"
					       id="id_thermostat_time_{{ forloop.counter }}"
					       class="mdl-textfield__input" type="time"
					       value="{{ thermostat.time|time:'H:i' }}" required>
				</div>
			</div>
		</div>
		<div style="width: 16px">&nbsp</div>
		<div style="flex:1">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="id_thermostat_temp_{{ forloop.counter }}"
				       class="mdl-textfield__label requiredField">
					Temperature
				</label>
				<div style="display: flex">
					<input name="thermostat_temp_{{ forloop.counter }}"
					       id="id_thermostat_temp_{{ forloop.counter }}"
					       class="mdl-textfield__input" value="{{ thermostat.setting }}"
					       type="number" style="text-align: right; margin-top: 6px" required>
					<div style="margin-top: 3px; margin-left: 3px; color: #666;">°C</div>
				</div>
			</div>
		</div>
	</div>
{% empty %}
	<div style="display: flex">
		<div style="flex:1">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="id_thermostat_time_1"
				       class="mdl-textfield__label requiredField">
					Start Time
				</label>
				<div style="display: flex">
					<input name="thermostat_time_1"
					       id="id_thermostat_time_1"
					       class="mdl-textfield__input" type="time"
					       value="18:00" required>
				</div>
			</div>
		</div>
		<div style="width: 16px">&nbsp</div>
		<div style="flex:1">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="id_thermostat_temp_1"
				       class="mdl-textfield__label requiredField">
					Temperature
				</label>
				<div style="display: flex">
					<input name="thermostat_temp_1"
					       id="id_thermostat_temp_1"
					       class="mdl-textfield__input" value="20.0"
					       type="number" style="text-align: right; margin-top: 6px" required>
					<div style="margin-top: 3px; margin-left: 3px; color: #666;">°C</div>
				</div>
			</div>
		</div>
	</div>
	<div style="display: flex">
		<div style="flex:1">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="id_thermostat_time_2"
				       class="mdl-textfield__label requiredField">
					Start Time
				</label>
				<div style="display: flex">
					<input name="thermostat_time_2"
					       id="id_thermostat_time_2"
					       class="mdl-textfield__input" type="time"
					       value="22:00" required>
				</div>
			</div>
		</div>
		<div style="width: 16px">&nbsp</div>
		<div style="flex:1">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<label for="id_thermostat_temp_2"
				       class="mdl-textfield__label requiredField">
					Temperature
				</label>
				<div style="display: flex">
					<input name="thermostat_temp_2"
					       id="id_thermostat_temp_2"
					       class="mdl-textfield__input" value="0"
					       type="number" style="text-align: right; margin-top: 6px" required>
					<div style="margin-top: 3px; margin-left: 3px; color: #666;">°C</div>
				</div>
			</div>
		</div>
	</div>
{% endfor %}



<div class="mdl-typography--subhead">Boiler</div>

<div id="div_id_boiler_type">
	<div style="padding-top: 0" class="mdl-textfield mdl-js-textfield">
		<label class="mdl-typography--caption mdl-color-text--primary requiredField" for="id_hub">
			Boiler Type
		</label>
		<label class="mdl-textfield__label"></label>
		<div><i class="material-icons" style="position: absolute; right: 0; z-index: -10;">arrow_drop_down</i>
			{% crispy_field form.boiler_type 'class' 'mdl-textfield__input' 'style' '-webkit-appearance: none; -moz-appearance: none; appearance: none; padding-right: 24px; border-radius: 0' %}
		</div>
	</div>
</div>

<div style="display: flex">
	<div id="div_id_boiler_manufacturer" style="flex:1">
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<label for="id_boiler_manufacturer" class="mdl-textfield__label ">
				Boiler manufacturer
			</label>
			<datalist id="boilers">
				<option value="Worcester">
				<option value="Vaillant">
				<option value="Vokera">
				<option value="Baxi">
				<option value="Biasi">
				<option value="Ideal">
				<option value="Firebird">
				<option value="Alpha">
			</datalist>
			<input class="textinput textInput mdl-textfield__input" id="id_boiler_manufacturer"
			       maxlength="255" name="boiler_manufacturer" list="boilers" type="text"
			       value="{{ deployment.boiler_manufacturer }}">
		</div>
	</div>
	<div style="width: 24px">&nbsp</div>
	<div id="div_id_boiler_model" style="flex:1">
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<label for="id_boiler_model" class="mdl-textfield__label ">
				Boiler model
			</label>
			{% crispy_field form.boiler_model 'class' 'mdl-textfield__input' %}
		</div>
	</div>
</div>
<div style="display: flex">
	<div id="div_id_boiler_output" style="flex:1">
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<label for="id_boiler_output" class="mdl-textfield__label ">
				Boiler output
			</label>
			<div style="display: flex">
				{% crispy_field form.boiler_output 'class' 'mdl-textfield__input' 'style' 'text-align:right' %}
				<div style="margin-top: 3px; margin-left: 3px; color: #666;" title="kilowatt">kW
				</div>
			</div>
		</div>
	</div>
	<div style="width: 24px">&nbsp</div>
	<div id="div_id_boiler_efficiency" style="flex:1">
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<label for="id_boiler_efficiency" class="mdl-textfield__label ">
				Boiler efficiency
			</label>
			<div style="display: flex">
				{% crispy_field form.boiler_efficiency 'class' 'mdl-textfield__input' 'style' 'text-align:right' %}
				<div style="margin-top: 3px; margin-left: 3px; color: #666;">%</div>
			</div>
		</div>
	</div>
</div>

src/app/deployments/templates/deployments/deployment_list.html
{% extends 'chariot/base.html' %}

{% block scripts %}
	<script>
	    var fragmentURL = "{% url 'deployments:fragment' 1234 %}";
	</script>

	<script src="/scripts/jquery.min.js"></script>
	<script src="/scripts/deployment_refresh.js"></script>
{% endblock %}

{% block content %}
<div class="mdl-grid" style="padding-bottom: 72px">
	{% for deployment in deployments %}
		<a href="{% url 'deployments:view' deployment.id %}" style="text-decoration: none" class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col mdl-cell--1-offset-tablet" data-deployment="{{deployment.id}}">
			{% include "deployments/deployment_fragment.html" with deployment=deployment firstload=firstload %}
		</a>
	{% empty %}
	<div class="mdl-typography--text-center">
		No deployments active!
	</div>
	{% endfor %}
</div>
{% endblock %}

{% block fab %}
<a href="{% url 'deployments:create' %}"
   class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored"
   style="position: fixed; right: 32px; bottom: 32px; z-index: 100;"
   title="Add Deployment">
	<i class="material-icons">add</i>
</a>
{% endblock %}

src/app/deployments/templates/deployments/deployment_update.html
{% extends 'chariot/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Deployment{% endblock %}

{% block content %}
	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--6-col mdl-cell--3-offset-desktop mdl-cell--1-offset-tablet">

			<form class="uniForm" method="post" enctype="multipart/form-data">

				{% include "deployments/deployment_fields.html" with deployment=deployment %}
				<input type="submit" value="Update"
				       class="submit submitButton mdl-button mdl-js-button button_right mdl-button--raised mdl-button--colored"
				       id="submit-id-add_hub">
			</form>
		</div>
	</div>
{% endblock content %}