src/app/chariot/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.views import static

from deployments.views import DeploymentListView
from hubs.views import HubCreateView
from .views import login_view, create_admin_view, DeviceListView

admin.autodiscover()

urlpatterns = [
    url(r'^$', DeploymentListView.as_view(), name='home'),
    url(r'^accounts/create/$', create_admin_view, name='auth_create_admin'),
    url(r'^accounts/login/$', login_view, name='auth_login'),
    url(r'^accounts/logout/$', logout_then_login, name='auth_logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('hubs.urls', namespace='hubs')),
    url(r'^deployments/', include('deployments.urls', namespace='deployments')),
    url(r'^devices', DeviceListView.as_view(), name='devices'),
    url(r'^graphs/', include('graphs.urls', namespace='graphs')),
    url(r'^hub/create', HubCreateView.as_view(), name='create_hub'),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
]

src/app/deployments/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^create', DeploymentCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)$', DeploymentView.as_view(), name='view'),
    url(r'^(?P<pk>\d+)/update', DeploymentUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/end$', DeploymentEndView.as_view(), name='end'),
    url(r'^(?P<pk>\d+)/start$', DeploymentStartView.as_view(), name='start'),
    url(r'^(?P<pk>\d+)/fragment$', DeploymentDetailView.as_view(), name='fragment'),
    url(r'^(?P<pk>\d+)/sensor/(?P<id>\d+)$', DeploymentSensorView.as_view(), name='sensor'),

    url(r'^annotation$', DeploymentAnnotationCreate.as_view(), name='annotation-create'),
    url(r'^annotation/(?P<pk>\d+)$', DeploymentAnnotationUpdate.as_view(),
        name='annotation-update'),
    url(r'^annotation/(?P<pk>\d+)/delete$', DeploymentAnnotationDelete.as_view(),
        name='annotation-delete'),
]

src/app/graphs/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^(?P<pk>\d+)$', DeploymentGraphView.as_view(), name='deployment'),
    url(r'^(?P<pk>\d+)/prediction', DeploymentPredictionView.as_view(), name='prediction'),
    url(r'^(?P<pk>\d+)/data', get_all_data, name='data'),
]

src/app/hubs/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^deployments', DeploymentListView.as_view(), name='deployments'),
    url(r'^deployment/(?P<pk>\d+)$', DeploymentView.as_view(), name='data'),
    url(r'^deployment/(?P<pk>\d+)/data', DataView.as_view(), name='data'),
    url(r'^deployment/(?P<pk>\d+)/latest', LatestDataView.as_view(), name='latest'),
    url(r'^deployment/(?P<pk>\d+)/prediction', DeploymentPrediction.as_view(), name='prediction'),
    url(r'^hub/(?P<id>[\w:-]+)/ping', HubPingView.as_view(), name='ping'),
    url(r'^hub/(?P<id>[\w:-]+)/sensors', SensorListView.as_view(), name='sensors'),
    url(r'^hub/(?P<id>[\w:-]+)/token', get_token, name='token'),
    url(r'^reading', SensorReading.as_view(), name='reading'),
]

src/app/graphs/views.py
import datetime
import json

from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import StreamingHttpResponse
from django.views.generic import DetailView

from chariot import utils
from chariot.influx import select
from chariot.mixins import BackButtonMixin, LoginRequiredMixin
from deployments.models import Deployment, DeploymentAnnotation
from graphs import simplify


def query(deployment, sensor, channel, start=None, end=None, aggregation="2m"):
    query_obj = select("MEAN").from_table(channel.id) \
        .where('deployment').eq(deployment.pk) \
        .where('sensor').eq(sensor.id)
    if start:
        query_obj = query_obj.where('time').gte(start)

    if end:
        query_obj = query_obj.where('time').lte(end)

    if not start and not end:
        query_obj = query_obj.where('time').lte_now()

    query_obj = query_obj.group_by_time(aggregation).fill_none().limit(10000)

    return query_obj.fetch()


def last(deployment, sensor, channel):
    query_obj = select("LAST").from_table(channel.id) \
        .where('deployment').eq(deployment.pk) \
        .where('sensor').eq(sensor.id)

    return query_obj.fetch()


def generate_data(deployment_id, sensors=None, channels=None, simplified=True, start=None,
                  end=None, aggregate=None):
    try:
        yield '{"sensors":['
        deployment = Deployment.objects.get(pk=deployment_id)
        first_sensor = True
        for sensor in deployment.sensors.all():
            if sensors and sensor.sensor.id not in sensors:
                continue
            if first_sensor:
                first_sensor = False
            else:
                yield ','
            yield '{"id":' + sensor.sensor.id + ','
            yield '"name":"' + sensor.sensor.name + '",'
            yield '"location":"' + sensor.location + '",'
            if sensor.cost:
                yield '"cost":' + str(sensor.cost) + ','
            yield '"channels":['

            first_channel = True
            for channel in sensor.sensor.channels.all():
                if channels != 'all' and (
                            channel.hidden or (channels and channel.id not in channels)):
                    continue
                aggregation = channel.aggregation
                if not simplified:
                    aggregation = '10s'
                elif aggregate:
                    aggregation = aggregate
                response = query(deployment, sensor.sensor, channel, start, end, aggregation)
                first_value = True
                while response.has_data():
                    if simplified:
                        data = simplify.simplify(response.data, 0.3)
                    else:
                        data = response.data
                    for value in data:
                        if first_value:
                            first_value = False
                            if first_channel:
                                first_channel = False
                            else:
                                yield ','
                            yield '{"id":"' + channel.id + '",'
                            yield '"name":"' + channel.name + '",'
                            yield '"units":"' + channel.units + '",'
                            yield '"data":['
                        else:
                            yield ','
                        yield '{"time":' + str(value['time']) + ','
                        yield '"value":' + str(value['mean']) + '}'

                    if response.is_partial():
                        response.next()
                    else:
                        break

                if not first_value:
                    yield ']}'

            yield ']}'
        yield '],'
        yield '"annotations":['
        annotations = DeploymentAnnotation.objects.filter(deployment=deployment_id)
        first_annotation = True
        for annotation in annotations:
            if first_annotation:
                first_annotation = False
            else:
                yield ','
            obj = utils.to_dict(annotation)
            yield json.dumps(obj)
        yield ']}'
    except Exception as e:
        yield e


def get_all_data(request, pk):
    return StreamingHttpResponse(generate_data(pk), content_type="application/json")


class DeploymentPredictionView(LoginRequiredMixin, BackButtonMixin, DetailView):
    model = Deployment
    template_name = 'graphs/deployment_prediction.html'

    def get_back_url(self):
        return reverse('deployments:update', args=(self.object.id,))


class DeploymentGraphView(LoginRequiredMixin, BackButtonMixin, DetailView):
    model = Deployment
    template_name = 'graphs/deployment_graph.html'

    def get_back_url(self):
        return reverse('deployments:update', args=(self.object.id,))

    def get_context_data(self, **kwargs):
        context = super(DeploymentGraphView, self).get_context_data(**kwargs)
        deployment = self.get_object()

        if deployment.start_date is None:
            raise Http404("Deployment not started")

        context['dateTo'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        context['dateFrom'] = deployment.start_date.strftime("%Y-%m-%d %H:%M:%S")
        return context

src/app/graphs/templates/graphs/deployment_graph.html
{% extends 'chariot/base.html' %}

{% block scripts %}
<script type="text/javascript">
	var DATA_URL = "{% url 'graphs:data' deployment.id %}";
	var ANNOTATION_URL = "{% url 'deployments:annotation-create' %}";
	var DEPLOYMENT_ID = {{ deployment.id }};
	var server_url = '{{ ROOT_URL }}/';
	var dataStart = '{{ dateFrom }}';
	var dataEnd = '{{ dateTo }}';

</script>
<script src="/scripts/moment.min.js"></script>
<!--  JQUERY -->
<script src="/scripts/jquery.min.js"></script>
<script src="/scripts/jquery-ui.min.js"></script>
<script src="/scripts/jquery.daterangepicker.min.js"></script>
<link rel="stylesheet" href="/styles/daterangepicker.min.css">
<!--- D3 --->
<script src="/scripts/d3.min.js"></script>
<script src="/scripts/d3.time.js"></script>
<!-- FE scripts and CSS -->
<script src="/scripts/fe.datastore.js"></script>
<script src="/scripts/fe.logger.js"></script>
<script src="/scripts/fe.logger.plot.js"></script>
<script src="/scripts/fe.logger.annotation.carpet.js"></script>
<script src="/scripts/fe.logger.selection.rubberband.js"></script>
<!-- Javascript -->
<script src="/scripts/graph.js"></script>
<link rel="stylesheet" href="/styles/graph.css">
{% endblock %}

{% block docTitle %}{{ deployment.client_name }} Deployment Sensor Data{% endblock %}
{% block title %}{{ deployment.client_name }} Deployment{% endblock %}

{% block toolbar %}
<button id="dateFilter" type="button" class="mdl-button mdl-js-button">
    All Dates
</button>

<button id="zoomIn" type="button" class="mdl-button mdl-js-button mdl-button--icon" title="Zoom In" disabled>
    <i class="material-icons">zoom_in</i>
</button>
<button id="zoomOut" type="button" class="mdl-button mdl-js-button mdl-button--icon" title="Zoom Out" disabled>
    <i class="material-icons">zoom_out</i>
</button>
{% endblock %}

{% block content %}
<div id="load-spinner">
    <div class="mdl-spinner mdl-js-spinner is-active"></div>
</div>

<div id="chart"></div>

<div style="overflow-y: auto">
    <div id="axisMenu" style="padding-top: 16px"></div>

    <div id="toggleAnnotations" class="visibility-item">
        <i class="material-icons">visibility</i>
        <div>Annotations</div>
    </div>

    <div id="visibilityMenu"></div>
</div>

<form id="annotations-edit-dialog">
    {% csrf_token %}
    <input type="hidden" id="an_deployment" name="deployment"/>
    <input type="hidden" id="an_annotation"/>
    <input type="hidden" id="an_layer" name="layer"/>
    <input type="hidden" id="an_start" name="start"/>
    <input type="hidden" id="an_end" name="end"/>
    <div class="mdl-shadow--2dp" style="background: #FFF; width: 350px">
        <div style="padding: 16px">
            <div id="an_textfield" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <label for="an_text" class="mdl-textfield__label">Annotation</label>
                <input name="text" type="text" class="mdl-textfield__input" id="an_text" autocomplete="off">
            </div>
            <div><span id="anno_start"></span> &ndash; <span id="anno_end"></span></div>
        </div>
        <div style="display: flex; justify-content: flex-end; padding: 4px;">
            <button id="annotation-delete" type="button" class="mdl-button mdl-js-button">Delete</button>
            <button id="annotation-save" type="submit" class="mdl-button mdl-js-button mdl-button--primary">Save
            </button>
        </div>
    </div>
</form>

<button id="addAnnotation"
        class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored"
        title="Add Deployment">
    <i class="material-icons">add</i>
</button>

<div id="svg-temp" hidden>test</div>
{% endblock %}

src/app/graphs/templates/graphs/deployment_prediction.html
{% extends 'chariot/base.html' %}

{% block scripts %}
	<script src="/scripts/Chart.min.js"></script>
	<style>
		.mdl-layout__content {
			display: inline-flex;
			flex-direction: column;
			margin: 16px;
		}

		.mdl-slider.is-upgraded::-webkit-slider-thumb {
			zoom: 1.5;
		}

		#warning {
			display: none;
			background-color: #dce775;
			padding: 8px;
		}
	</style>
{% endblock %}

{% block docTitle %}{{ deployment.client_name }} Deployment Sensor Data{% endblock %}
{% block title %}{{ deployment.client_name }} Deployment{% endblock %}

{% block content %}
	<div style="align-self: center"><div id="warning"></div></div>
	<div style="flex: 1">
		<canvas id="canvas"></canvas>
	</div>
	<div style="text-align: center">Thermostat Temperature: <span id="set_label">20</span>°C</div>
	<div style="padding: 8px 0">
		<input id="set_slider" class="mdl-slider mdl-js-slider" type="range" min="0" max="10" value="0">
	</div>
	<div style="text-align: center">Outside Temperature Change: <span id="ext_label">0</span>°C</div>
	<div style="padding: 8px 0">
		<input id="ext_slider" class="mdl-slider mdl-js-slider" type="range" min="0" max="10" value="0">
	</div>

	<script>
		{% autoescape off %}
			const predictions = {{ deployment.prediction }};
		{% endautoescape %}

		if(predictions.Error) {
			document.getElementById('warning').innerText = predictions.Error;
			document.getElementById('warning').style.display = 'block';
		} else if(predictions.Warning) {
			document.getElementById('warning').innerText = predictions.Warning;
			document.getElementById('warning').style.display = 'block';
		}

		if('What_If_Predictions' in predictions) {
			const ctx = document.getElementById("canvas").getContext('2d');
			var chart = new Chart(ctx, {
				type: 'line',
				data: {
					labels: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"],
					datasets: [{
						backgroundColor: 'rgba(13, 71, 161, 0.5)',
						borderColor: '#0d47a1',
						data: predictions['What_If_Predictions'][0]['Hourly_Cost_Prediction']
					}]
				},
				options: {
					legend: {
						display: false
					},
					responsive: true,
					maintainAspectRatio: false,
					scales: {
						yAxes: [{
							scaleLabel: {
								display: true,
								labelString: 'Cost'
							}
						}],
						xAxes: [{
							scaleLabel: {
								display: true,
								labelString: 'Hours'
							},
							gridLines: {
								display: false
							}
						}]
					}
				}
			});

			var set_min = 1000;
			var set_max = -1000;
			var ext_min = 1000;
			var ext_max = -1000;
			for (const prediction of predictions['What_If_Predictions']) {
				const conditions = prediction['What_If_Conditions'];
				set_max = Math.max(set_max, conditions['Set_Point']);
				set_min = Math.min(set_min, conditions['Set_Point']);

				ext_max = Math.max(ext_max, conditions['Change_In_External_Temperature']);
				ext_min = Math.min(ext_min, conditions['Change_In_External_Temperature']);
			}

			const set_slider = document.getElementById('set_slider');
			const ext_slider = document.getElementById('ext_slider');

			set_slider.min = set_min;
			set_slider.max = set_max;
			set_slider.value = ((set_max - set_min) / 2) + set_min;
			ext_slider.min = ext_min;
			ext_slider.max = ext_max;
			ext_slider.value = ((ext_max - ext_min) / 2) + ext_min;

			function update() {
				const set_point = set_slider.value;
				const ext_temp = ext_slider.value;

				document.getElementById('set_label').innerHTML = set_point;
				document.getElementById('ext_label').innerHTML = ext_temp;
				for (const prediction of predictions['What_If_Predictions']) {
					const conditions = prediction['What_If_Conditions'];
					if (conditions['Set_Point'] == set_point && conditions['Change_In_External_Temperature'] == ext_temp) {
						chart.data.datasets[0].data = prediction['Hourly_Cost_Prediction'];
						chart.update();
					}
				}
			}

			update();

			document.getElementById('set_slider').oninput = update;
			document.getElementById('ext_slider').oninput = update;
		} else {
			document.getElementById('set_slider').style.display = 'none';
			document.getElementById('ext_slider').style.display = 'none';

		}
	</script>
{% endblock %}